services:
    postgres:
        container_name: postgres
        image: postgres
        ports:
            - '5433:5432'
        environment:
            - POSTGRES_PASSWORD=golang
            - POSTGRES_DB=coffee_db
            - POSTGRES_USER=golang
        networks:
            - coffeenet

    backend:
        image: taufikharahap/coffeeshop:3
        ports:
            - '8089:8081'
        environment:
            - DB_HOST=postgres
        networks:
            - coffeenet

networks:
    coffeenet:
          name: 'devnet'
          external: true