services:
    postgres:
        image: postgres:16.1-alpine3.18
        ports:
            - '5433:5432'
        environment:
            - POSTGRES_PASSWORD=golang
            - POSTGRES_DB=coffee_db
            - POSTGRES_USER=golang
        networks:
            - coffeenet

    backend:
        image: taufikharahap/coffeeshop:2
        ports:
            - '8089:8081'
        environment:
            - DB_HOST=some-postgres
        networks:
            - coffeenet

networks:
    coffeenet:
          name: 'devnet'
          external: true